apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zendesk-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zendesk-db-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: /tmp/zendesk-db-data