apiVersion: v1
kind: Service
metadata:
  name: zendesk-grpc-service
  labels:
    app: zendesk-grpc-service
spec:
  type: ClusterIP
  selector:
    app: zendesk-grpc-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051 