// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: proto/ratingService/v1/rating_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DateRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRangeRequest) Reset() {
	*x = DateRangeRequest{}
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRangeRequest) ProtoMessage() {}

func (x *DateRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRangeRequest.ProtoReflect.Descriptor instead.
func (*DateRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratingService_v1_rating_service_proto_rawDescGZIP(), []int{0}
}

func (x *DateRangeRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *DateRangeRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type ScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratingService_v1_rating_service_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ScoreChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentStart  string                 `protobuf:"bytes,1,opt,name=current_start,json=currentStart,proto3" json:"current_start,omitempty"`
	CurrentEnd    string                 `protobuf:"bytes,2,opt,name=current_end,json=currentEnd,proto3" json:"current_end,omitempty"`
	PreviousStart string                 `protobuf:"bytes,3,opt,name=previous_start,json=previousStart,proto3" json:"previous_start,omitempty"`
	PreviousEnd   string                 `protobuf:"bytes,4,opt,name=previous_end,json=previousEnd,proto3" json:"previous_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreChangeRequest) Reset() {
	*x = ScoreChangeRequest{}
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreChangeRequest) ProtoMessage() {}

func (x *ScoreChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreChangeRequest.ProtoReflect.Descriptor instead.
func (*ScoreChangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratingService_v1_rating_service_proto_rawDescGZIP(), []int{2}
}

func (x *ScoreChangeRequest) GetCurrentStart() string {
	if x != nil {
		return x.CurrentStart
	}
	return ""
}

func (x *ScoreChangeRequest) GetCurrentEnd() string {
	if x != nil {
		return x.CurrentEnd
	}
	return ""
}

func (x *ScoreChangeRequest) GetPreviousStart() string {
	if x != nil {
		return x.PreviousStart
	}
	return ""
}

func (x *ScoreChangeRequest) GetPreviousEnd() string {
	if x != nil {
		return x.PreviousEnd
	}
	return ""
}

type ScoreChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentScore  float64                `protobuf:"fixed64,1,opt,name=current_score,json=currentScore,proto3" json:"current_score,omitempty"`
	PreviousScore float64                `protobuf:"fixed64,2,opt,name=previous_score,json=previousScore,proto3" json:"previous_score,omitempty"`
	Change        float64                `protobuf:"fixed64,3,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreChangeResponse) Reset() {
	*x = ScoreChangeResponse{}
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreChangeResponse) ProtoMessage() {}

func (x *ScoreChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreChangeResponse.ProtoReflect.Descriptor instead.
func (*ScoreChangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratingService_v1_rating_service_proto_rawDescGZIP(), []int{3}
}

func (x *ScoreChangeResponse) GetCurrentScore() float64 {
	if x != nil {
		return x.CurrentScore
	}
	return 0
}

func (x *ScoreChangeResponse) GetPreviousScore() float64 {
	if x != nil {
		return x.PreviousScore
	}
	return 0
}

func (x *ScoreChangeResponse) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

type CategoryScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	ScoresByDate  map[string]float64     `protobuf:"bytes,2,rep,name=scores_by_date,json=scoresByDate,proto3" json:"scores_by_date,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	AverageScore  float64                `protobuf:"fixed64,3,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"`
	RatingsCount  int32                  `protobuf:"varint,4,opt,name=ratings_count,json=ratingsCount,proto3" json:"ratings_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryScore) Reset() {
	*x = CategoryScore{}
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryScore) ProtoMessage() {}

func (x *CategoryScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryScore.ProtoReflect.Descriptor instead.
func (*CategoryScore) Descriptor() ([]byte, []int) {
	return file_proto_ratingService_v1_rating_service_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryScore) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryScore) GetScoresByDate() map[string]float64 {
	if x != nil {
		return x.ScoresByDate
	}
	return nil
}

func (x *CategoryScore) GetAverageScore() float64 {
	if x != nil {
		return x.AverageScore
	}
	return 0
}

func (x *CategoryScore) GetRatingsCount() int32 {
	if x != nil {
		return x.RatingsCount
	}
	return 0
}

type CategoryScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryScore       `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryScoresResponse) Reset() {
	*x = CategoryScoresResponse{}
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryScoresResponse) ProtoMessage() {}

func (x *CategoryScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryScoresResponse.ProtoReflect.Descriptor instead.
func (*CategoryScoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratingService_v1_rating_service_proto_rawDescGZIP(), []int{5}
}

func (x *CategoryScoresResponse) GetCategories() []*CategoryScore {
	if x != nil {
		return x.Categories
	}
	return nil
}

type TicketScore struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TicketId       string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	CategoryScores map[string]float64     `protobuf:"bytes,2,rep,name=category_scores,json=categoryScores,proto3" json:"category_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TicketScore) Reset() {
	*x = TicketScore{}
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketScore) ProtoMessage() {}

func (x *TicketScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketScore.ProtoReflect.Descriptor instead.
func (*TicketScore) Descriptor() ([]byte, []int) {
	return file_proto_ratingService_v1_rating_service_proto_rawDescGZIP(), []int{6}
}

func (x *TicketScore) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *TicketScore) GetCategoryScores() map[string]float64 {
	if x != nil {
		return x.CategoryScores
	}
	return nil
}

type TicketScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*TicketScore         `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketScoresResponse) Reset() {
	*x = TicketScoresResponse{}
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketScoresResponse) ProtoMessage() {}

func (x *TicketScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratingService_v1_rating_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketScoresResponse.ProtoReflect.Descriptor instead.
func (*TicketScoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratingService_v1_rating_service_proto_rawDescGZIP(), []int{7}
}

func (x *TicketScoresResponse) GetTickets() []*TicketScore {
	if x != nil {
		return x.Tickets
	}
	return nil
}

var File_proto_ratingService_v1_rating_service_proto protoreflect.FileDescriptor

const file_proto_ratingService_v1_rating_service_proto_rawDesc = "" +
	"\n" +
	"+proto/ratingService/v1/rating_service.proto\x12\x06rating\"L\n" +
	"\x10DateRangeRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"%\n" +
	"\rScoreResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\"\xa4\x01\n" +
	"\x12ScoreChangeRequest\x12#\n" +
	"\rcurrent_start\x18\x01 \x01(\tR\fcurrentStart\x12\x1f\n" +
	"\vcurrent_end\x18\x02 \x01(\tR\n" +
	"currentEnd\x12%\n" +
	"\x0eprevious_start\x18\x03 \x01(\tR\rpreviousStart\x12!\n" +
	"\fprevious_end\x18\x04 \x01(\tR\vpreviousEnd\"y\n" +
	"\x13ScoreChangeResponse\x12#\n" +
	"\rcurrent_score\x18\x01 \x01(\x01R\fcurrentScore\x12%\n" +
	"\x0eprevious_score\x18\x02 \x01(\x01R\rpreviousScore\x12\x16\n" +
	"\x06change\x18\x03 \x01(\x01R\x06change\"\x85\x02\n" +
	"\rCategoryScore\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12M\n" +
	"\x0escores_by_date\x18\x02 \x03(\v2'.rating.CategoryScore.ScoresByDateEntryR\fscoresByDate\x12#\n" +
	"\raverage_score\x18\x03 \x01(\x01R\faverageScore\x12#\n" +
	"\rratings_count\x18\x04 \x01(\x05R\fratingsCount\x1a?\n" +
	"\x11ScoresByDateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"O\n" +
	"\x16CategoryScoresResponse\x125\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x15.rating.CategoryScoreR\n" +
	"categories\"\xbf\x01\n" +
	"\vTicketScore\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12P\n" +
	"\x0fcategory_scores\x18\x02 \x03(\v2'.rating.TicketScore.CategoryScoresEntryR\x0ecategoryScores\x1aA\n" +
	"\x13CategoryScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"E\n" +
	"\x14TicketScoresResponse\x12-\n" +
	"\atickets\x18\x01 \x03(\v2\x13.rating.TicketScoreR\atickets2\xac\x02\n" +
	"\rRatingService\x12?\n" +
	"\fOverallScore\x12\x18.rating.DateRangeRequest\x1a\x15.rating.ScoreResponse\x12F\n" +
	"\vScoreChange\x12\x1a.rating.ScoreChangeRequest\x1a\x1b.rating.ScoreChangeResponse\x12J\n" +
	"\x0eCategoryScores\x12\x18.rating.DateRangeRequest\x1a\x1e.rating.CategoryScoresResponse\x12F\n" +
	"\fTicketScores\x12\x18.rating.DateRangeRequest\x1a\x1c.rating.TicketScoresResponseB\x1cZ\x1azendesk_grpc_service/protob\x06proto3"

var (
	file_proto_ratingService_v1_rating_service_proto_rawDescOnce sync.Once
	file_proto_ratingService_v1_rating_service_proto_rawDescData []byte
)

func file_proto_ratingService_v1_rating_service_proto_rawDescGZIP() []byte {
	file_proto_ratingService_v1_rating_service_proto_rawDescOnce.Do(func() {
		file_proto_ratingService_v1_rating_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ratingService_v1_rating_service_proto_rawDesc), len(file_proto_ratingService_v1_rating_service_proto_rawDesc)))
	})
	return file_proto_ratingService_v1_rating_service_proto_rawDescData
}

var file_proto_ratingService_v1_rating_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_ratingService_v1_rating_service_proto_goTypes = []any{
	(*DateRangeRequest)(nil),       // 0: rating.DateRangeRequest
	(*ScoreResponse)(nil),          // 1: rating.ScoreResponse
	(*ScoreChangeRequest)(nil),     // 2: rating.ScoreChangeRequest
	(*ScoreChangeResponse)(nil),    // 3: rating.ScoreChangeResponse
	(*CategoryScore)(nil),          // 4: rating.CategoryScore
	(*CategoryScoresResponse)(nil), // 5: rating.CategoryScoresResponse
	(*TicketScore)(nil),            // 6: rating.TicketScore
	(*TicketScoresResponse)(nil),   // 7: rating.TicketScoresResponse
	nil,                            // 8: rating.CategoryScore.ScoresByDateEntry
	nil,                            // 9: rating.TicketScore.CategoryScoresEntry
}
var file_proto_ratingService_v1_rating_service_proto_depIdxs = []int32{
	8, // 0: rating.CategoryScore.scores_by_date:type_name -> rating.CategoryScore.ScoresByDateEntry
	4, // 1: rating.CategoryScoresResponse.categories:type_name -> rating.CategoryScore
	9, // 2: rating.TicketScore.category_scores:type_name -> rating.TicketScore.CategoryScoresEntry
	6, // 3: rating.TicketScoresResponse.tickets:type_name -> rating.TicketScore
	0, // 4: rating.RatingService.OverallScore:input_type -> rating.DateRangeRequest
	2, // 5: rating.RatingService.ScoreChange:input_type -> rating.ScoreChangeRequest
	0, // 6: rating.RatingService.CategoryScores:input_type -> rating.DateRangeRequest
	0, // 7: rating.RatingService.TicketScores:input_type -> rating.DateRangeRequest
	1, // 8: rating.RatingService.OverallScore:output_type -> rating.ScoreResponse
	3, // 9: rating.RatingService.ScoreChange:output_type -> rating.ScoreChangeResponse
	5, // 10: rating.RatingService.CategoryScores:output_type -> rating.CategoryScoresResponse
	7, // 11: rating.RatingService.TicketScores:output_type -> rating.TicketScoresResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_ratingService_v1_rating_service_proto_init() }
func file_proto_ratingService_v1_rating_service_proto_init() {
	if File_proto_ratingService_v1_rating_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ratingService_v1_rating_service_proto_rawDesc), len(file_proto_ratingService_v1_rating_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ratingService_v1_rating_service_proto_goTypes,
		DependencyIndexes: file_proto_ratingService_v1_rating_service_proto_depIdxs,
		MessageInfos:      file_proto_ratingService_v1_rating_service_proto_msgTypes,
	}.Build()
	File_proto_ratingService_v1_rating_service_proto = out.File
	file_proto_ratingService_v1_rating_service_proto_goTypes = nil
	file_proto_ratingService_v1_rating_service_proto_depIdxs = nil
}
