// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: proto/ratingService/v1/rating_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RatingService_OverallScore_FullMethodName   = "/rating.RatingService/OverallScore"
	RatingService_ScoreChange_FullMethodName    = "/rating.RatingService/ScoreChange"
	RatingService_CategoryScores_FullMethodName = "/rating.RatingService/CategoryScores"
	RatingService_TicketScores_FullMethodName   = "/rating.RatingService/TicketScores"
)

// RatingServiceClient is the client API for RatingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatingServiceClient interface {
	OverallScore(ctx context.Context, in *DateRangeRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	ScoreChange(ctx context.Context, in *ScoreChangeRequest, opts ...grpc.CallOption) (*ScoreChangeResponse, error)
	CategoryScores(ctx context.Context, in *DateRangeRequest, opts ...grpc.CallOption) (*CategoryScoresResponse, error)
	TicketScores(ctx context.Context, in *DateRangeRequest, opts ...grpc.CallOption) (*TicketScoresResponse, error)
}

type ratingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRatingServiceClient(cc grpc.ClientConnInterface) RatingServiceClient {
	return &ratingServiceClient{cc}
}

func (c *ratingServiceClient) OverallScore(ctx context.Context, in *DateRangeRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, RatingService_OverallScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) ScoreChange(ctx context.Context, in *ScoreChangeRequest, opts ...grpc.CallOption) (*ScoreChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreChangeResponse)
	err := c.cc.Invoke(ctx, RatingService_ScoreChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) CategoryScores(ctx context.Context, in *DateRangeRequest, opts ...grpc.CallOption) (*CategoryScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryScoresResponse)
	err := c.cc.Invoke(ctx, RatingService_CategoryScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) TicketScores(ctx context.Context, in *DateRangeRequest, opts ...grpc.CallOption) (*TicketScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketScoresResponse)
	err := c.cc.Invoke(ctx, RatingService_TicketScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatingServiceServer is the server API for RatingService service.
// All implementations must embed UnimplementedRatingServiceServer
// for forward compatibility.
type RatingServiceServer interface {
	OverallScore(context.Context, *DateRangeRequest) (*ScoreResponse, error)
	ScoreChange(context.Context, *ScoreChangeRequest) (*ScoreChangeResponse, error)
	CategoryScores(context.Context, *DateRangeRequest) (*CategoryScoresResponse, error)
	TicketScores(context.Context, *DateRangeRequest) (*TicketScoresResponse, error)
	mustEmbedUnimplementedRatingServiceServer()
}

// UnimplementedRatingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRatingServiceServer struct{}

func (UnimplementedRatingServiceServer) OverallScore(context.Context, *DateRangeRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OverallScore not implemented")
}
func (UnimplementedRatingServiceServer) ScoreChange(context.Context, *ScoreChangeRequest) (*ScoreChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoreChange not implemented")
}
func (UnimplementedRatingServiceServer) CategoryScores(context.Context, *DateRangeRequest) (*CategoryScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategoryScores not implemented")
}
func (UnimplementedRatingServiceServer) TicketScores(context.Context, *DateRangeRequest) (*TicketScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TicketScores not implemented")
}
func (UnimplementedRatingServiceServer) mustEmbedUnimplementedRatingServiceServer() {}
func (UnimplementedRatingServiceServer) testEmbeddedByValue()                       {}

// UnsafeRatingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatingServiceServer will
// result in compilation errors.
type UnsafeRatingServiceServer interface {
	mustEmbedUnimplementedRatingServiceServer()
}

func RegisterRatingServiceServer(s grpc.ServiceRegistrar, srv RatingServiceServer) {
	// If the following call pancis, it indicates UnimplementedRatingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RatingService_ServiceDesc, srv)
}

func _RatingService_OverallScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).OverallScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_OverallScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).OverallScore(ctx, req.(*DateRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_ScoreChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).ScoreChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_ScoreChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).ScoreChange(ctx, req.(*ScoreChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_CategoryScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).CategoryScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_CategoryScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).CategoryScores(ctx, req.(*DateRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_TicketScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).TicketScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_TicketScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).TicketScores(ctx, req.(*DateRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RatingService_ServiceDesc is the grpc.ServiceDesc for RatingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rating.RatingService",
	HandlerType: (*RatingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OverallScore",
			Handler:    _RatingService_OverallScore_Handler,
		},
		{
			MethodName: "ScoreChange",
			Handler:    _RatingService_ScoreChange_Handler,
		},
		{
			MethodName: "CategoryScores",
			Handler:    _RatingService_CategoryScores_Handler,
		},
		{
			MethodName: "TicketScores",
			Handler:    _RatingService_TicketScores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ratingService/v1/rating_service.proto",
}
